2018-08-29 12:37:21,761 INFO: Microblog startup [in C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\__init__.py:54]
2018-08-29 12:37:25,988 ERROR: Exception on /index [GET] [in c:\users\tmosco\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tmosco\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tmosco\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\routes.py", line 23, in index
    form= PostsForm()
NameError: name 'PostsForm' is not defined
2018-08-29 12:37:29,179 ERROR: Exception on /index [GET] [in c:\users\tmosco\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tmosco\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tmosco\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\routes.py", line 23, in index
    form= PostsForm()
NameError: name 'PostsForm' is not defined
2018-08-29 13:35:04,303 ERROR: Exception on /index [GET] [in c:\users\tmosco\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tmosco\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tmosco\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\routes.py", line 23, in index
    form= PostsForm()
NameError: name 'PostsForm' is not defined
2018-08-29 13:35:29,002 INFO: Microblog startup [in C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\__init__.py:54]
2018-08-29 13:35:40,658 ERROR: Exception on /login [GET] [in c:\users\tmosco\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tmosco\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\routes.py", line 75, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\tmosco\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\tmosco\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\tmosco\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\tmosco\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\tmosco\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tmosco\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\templates\base.html", line 56, in top-level template code
    {% block content %} {% endblock %}
  File "C:\Users\Tmosco\workspace\PYHTHON\learning-flask\flaskmega\app\templates\login.html", line 33, in block "content"
    <p>Forgot Your Password? <a href="{{url_for('reset_password_request')}}">Click to Reset IT </a></p>
  File "c:\users\tmosco\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\tmosco\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\tmosco\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\tmosco\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\tmosco\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
